---
title: "R Notebook For Applied Data Science-Project I"
output:
  html_document: default
  html_notebook: default
runtime: shiny
---
```{r, message=FALSE, warning=FALSE, include=FALSE}
#NECESSARY PACKAGES
source("D:/Columbia University/Spring2017-Applied Data Science/Project_1_Bz2290/Spr2017-Proj1-bz2290/doc/Package.R")
#Functions needed
source("D:/Columbia University/Spring2017-Applied Data Science/Project_1_Bz2290/Spr2017-Proj1-bz2290/lib/Functions.R")
```

```{r, include=FALSE}
##PREPRCESSIONING OF THE DATA##

#Please modify the path within Preprocess.R
source("D:/Columbia University/Spring2017-Applied Data Science/Project_1_Bz2290/Spr2017-Proj1-bz2290/output/Preprocess.R")
```

```{r}
#The presidential inauguartion speeches were choosen based on the major war in both US and world history. The analysis applied to those speeches will reveal some interesting patterns and sometimes even surprises to out common understanding of what we think these speeches should be.
```

```{r}
#This notebook was prepared with the following environmental settings.
```


```{r, echo=FALSE}
print(R.version)
```

```{r}
#First let us take a look at the sentence length of each speech
```


```{r, echo=FALSE, fig.height=2.5, fig.width=2}
#Sentence Length
library(shiny)
shinyApp(
  ui = fluidPage(
      fluidRow(
      column(12,checkboxGroupInput("POP","President",speech.selected,selected = speech.selected,inline = TRUE))),
      theme=shinytheme("superhero"),
      fluidRow(
      column(12,plotOutput("beeswarm")))
  ),
  server = function(input,output,session){
    selected.data = reactive(
      {
        sentence = emotion.matrix[,1:4]
        sentence = subset(sentence,as.character(sentence$President) %in% input$POP)
        sentence$Pop = factor(sentence$President)
        sentence$Ordered=reorder(sentence$Pop,sentence$nword,mean,order=T)
        return(sentence)

      }
    )
    output$beeswarm = renderPlot(
      {
        par(mai=c(2.4,0.82,0.82,0.42))
        beeswarm(nword~Ordered, 
         data=selected.data(),
         horizontal = FALSE, 
         pch=19, col=alpha(brewer.pal(9, "Set2"), 0.6),
         cex=1, cex.axis=1.2, cex.lab=1.2,
         spacing=5/nlevels(selected.data()$Ordered),
         las=2,ylab="Number of words",
         xlab="",
         main="Inauguartion speeches")
      }
    )
  }
)
```

```{r}
#Generally, we see that all speeches have its majority amount of sentences only have smaller than or equal to 20 words.BUt if we start to examine individual speeches, first we find out that most presidents' first and second speech(if there are any), have the similiar distribution of sentence length. Only a small amount of presdeints have their second speech significantly smaller than the first one.
```

```{r}
#If we start to compare speeches given in tense moments and speeches given in rather peaceful or even prosper moments:

#We can see that in general, speeches give nin prosper time has a greater hortizonatal spread(namly has more sentences that are close to 20 words) than those are given during war or tense moments.
```


```{r}
#Next we take a look at the heatmap and Barplot of emotion:
#IN order to ease our comparsion, we use number 1 to 10 to denote the ten speeches we selected.
```

```{r, echo=FALSE}
#Heatmap & Barplot
shinyApp(
  ui=fluidPage(
    sidebarLayout(
        sidebarPanel(
   sliderInput("Pop","President",min=1,max=length(speech.selected),value=1,step=1)),
    mainPanel(
      tabsetPanel(
      tabPanel("Heatmap",uiOutput("ui_heatmap")),
      tabPanel("Barplot",plotOutput("Barplot"))
      ))
     )
    ),
  server = function(input,output){
    output$ui_heatmap <- renderUI({
    d3heatmapOutput("heatmap")
  })

  output$heatmap <- renderD3heatmap({ 
    d3heatmap(cor(emotion.matrix%>%filter(President==speech.selected[input$Pop])%>%select(anger:trust)),Rowv = FALSE, dendrogram = "row",Colv=FALSE,color="Blues") 
  })
      output$Barplot = renderPlot(
      {
        Emotion_Barplot(speech.selected[input$Pop])
      }
    )
    
    
  }
)
```

```{r}
#There is no surprise that the top 3 emotions that appear the most in the speeches given during peaceful time are majorityly postive emtions. But, surprisingly,When examine the barplot of our selected speeches given during the war time, we see that, except the second speech given by AbrhamLincoln, during which the civil war was about to end, all the other speeches tend to have the trust emotion the most, and relative positive amotion such as joy and anticipation also came second the most. There are only three time when begative emotion such as fear came to the first and the second, while two tims come from Lincoln's two speeches, and the last one came from FrankdRooselt's second speech. In addition, after the second speech, the postive words went back to be the top 2 emotions from Rooselevt's speech. This rather surprising pattern is interesting, as our general assumption was those speeches should not be very positive during war times. What is more, we can also observe that emtions like Joy,trust,anticipation and fear will come in top 4 every time.This patterns deserve a little bit of digging and we will examine that further in the next part.

#In addition to those, the heatmap reveals that the negative emotion sich as anger was usually related to fear and digust, where posiive emotion such as anticipitian is usually realted to joy.
```


```{r}
#Now we want to take a look at the sentence with positive emotions and try to find out more interesting part.
```

```{r}
#Joy-War time Speeches#
```

```{r, echo=FALSE, message=FALSE}
print(speech.selected[1])
Emotion_Sentences(pop=speech.selected[1])[5,]

print(speech.selected[2])
Emotion_Sentences(pop=speech.selected[2])[5,]

print(speech.selected[3])
Emotion_Sentences(pop=speech.selected[3])[5,]

print(speech.selected[4])
Emotion_Sentences(pop=speech.selected[4])[5,]

print(speech.selected[5])
Emotion_Sentences(pop=speech.selected[5])[5,]

print(speech.selected[6])
Emotion_Sentences(pop=speech.selected[6])[5,]

print(speech.selected[7])
Emotion_Sentences(pop=speech.selected[7])[5,]

print(speech.selected[8])
Emotion_Sentences(pop=speech.selected[8])[5,]

print(speech.selected[9])
Emotion_Sentences(pop=speech.selected[9])[5,]

print(speech.selected[10])
Emotion_Sentences(pop=speech.selected[10])[5,]
```

```{r}
#Joy-Peaecful time Speeches#
```

```{r, echo=FALSE, message=FALSE}
print(speech.selected[11])
Emotion_Sentences(pop=speech.selected[11])[5,]

print(speech.selected[12])
Emotion_Sentences(pop=speech.selected[12])[5,]

print(speech.selected[13])
Emotion_Sentences(pop=speech.selected[13])[5,]

print(speech.selected[14])
Emotion_Sentences(pop=speech.selected[14])[5,]
```

```{r}
#Trust-War time Speeches#
```

```{r, echo=FALSE, message=FALSE}
print(speech.selected[1])
Emotion_Sentences(pop=speech.selected[1])[8,]

print(speech.selected[2])
Emotion_Sentences(pop=speech.selected[2])[8,]

print(speech.selected[3])
Emotion_Sentences(pop=speech.selected[3])[8,]

print(speech.selected[4])
Emotion_Sentences(pop=speech.selected[4])[8,]

print(speech.selected[5])
Emotion_Sentences(pop=speech.selected[5])[8,]

print(speech.selected[6])
Emotion_Sentences(pop=speech.selected[6])[8,]

print(speech.selected[7])
Emotion_Sentences(pop=speech.selected[7])[8,]

print(speech.selected[8])
Emotion_Sentences(pop=speech.selected[8])[8,]

print(speech.selected[9])
Emotion_Sentences(pop=speech.selected[9])[8,]

print(speech.selected[10])
Emotion_Sentences(pop=speech.selected[10])[8,]
```

```{r}
#Trust-Peaecful time Speeches#
```

```{r, echo=FALSE, message=FALSE}
print(speech.selected[11])
Emotion_Sentences(pop=speech.selected[11])[8,]

print(speech.selected[12])
Emotion_Sentences(pop=speech.selected[12])[8,]

print(speech.selected[13])
Emotion_Sentences(pop=speech.selected[13])[8,]

print(speech.selected[14])
Emotion_Sentences(pop=speech.selected[14])[8,]
```

```{r}
#Anticipation-War time Speeches#
```

```{r, echo=FALSE, message=FALSE}
print(speech.selected[1])
Emotion_Sentences(pop=speech.selected[1])[2,]

print(speech.selected[2])
Emotion_Sentences(pop=speech.selected[2])[2,]

print(speech.selected[3])
Emotion_Sentences(pop=speech.selected[3])[2,]

print(speech.selected[4])
Emotion_Sentences(pop=speech.selected[4])[2,]

print(speech.selected[5])
Emotion_Sentences(pop=speech.selected[5])[2,]

print(speech.selected[6])
Emotion_Sentences(pop=speech.selected[6])[2,]

print(speech.selected[7])
Emotion_Sentences(pop=speech.selected[7])[2,]

print(speech.selected[8])
Emotion_Sentences(pop=speech.selected[8])[2,]

print(speech.selected[9])
Emotion_Sentences(pop=speech.selected[9])[2,]

print(speech.selected[10])
Emotion_Sentences(pop=speech.selected[10])[2,]
```

```{r}
#Anticipation-Peaecful time Speeches#
```

```{r, echo=FALSE, message=FALSE}
print(speech.selected[11])
Emotion_Sentences(pop=speech.selected[11])[2,]

print(speech.selected[12])
Emotion_Sentences(pop=speech.selected[12])[2,]

print(speech.selected[13])
Emotion_Sentences(pop=speech.selected[13])[2,]

print(speech.selected[14])
Emotion_Sentences(pop=speech.selected[14])[2,]
```

```{r}
#Fear-War time Speeches#
```

```{r, echo=FALSE, message=FALSE}
print(speech.selected[1])
Emotion_Sentences(pop=speech.selected[1])[4,]

print(speech.selected[2])
Emotion_Sentences(pop=speech.selected[2])[4,]

print(speech.selected[3])
Emotion_Sentences(pop=speech.selected[3])[4,]

print(speech.selected[4])
Emotion_Sentences(pop=speech.selected[4])[4,]

print(speech.selected[5])
Emotion_Sentences(pop=speech.selected[5])[4,]

print(speech.selected[6])
Emotion_Sentences(pop=speech.selected[6])[4,]

print(speech.selected[7])
Emotion_Sentences(pop=speech.selected[7])[4,]

print(speech.selected[8])
Emotion_Sentences(pop=speech.selected[8])[4,]

print(speech.selected[9])
Emotion_Sentences(pop=speech.selected[9])[4,]

print(speech.selected[10])
Emotion_Sentences(pop=speech.selected[10])[4,]
```

```{r}
#Fear-Peaecful time Speeches#
```

```{r, echo=FALSE, message=FALSE}
print(speech.selected[11])
Emotion_Sentences(pop=speech.selected[11])[4,]

print(speech.selected[12])
Emotion_Sentences(pop=speech.selected[12])[4,]

print(speech.selected[13])
Emotion_Sentences(pop=speech.selected[13])[4,]

print(speech.selected[14])
Emotion_Sentences(pop=speech.selected[14])[4,]
```
